--
-- PostgreSQL database dump
--

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg12+1)
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.chapter_progress DROP CONSTRAINT IF EXISTS fkv4lcvj8xomcv3tmeylctrldg;
ALTER TABLE IF EXISTS ONLY public.resource DROP CONSTRAINT IF EXISTS fkmeif6ix75gdnvpopg3d6gmaa6;
ALTER TABLE IF EXISTS ONLY public.chapter_progress DROP CONSTRAINT IF EXISTS fklk6rkos5dm8jxdpms4xo8ksov;
ALTER TABLE IF EXISTS ONLY public.chapter DROP CONSTRAINT IF EXISTS fkc9w9kmbmff4v3oeij0pa5vm2e;
DROP INDEX IF EXISTS public.idx_users_email;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_pkey;
ALTER TABLE IF EXISTS ONLY public.users DROP CONSTRAINT IF EXISTS users_email_key;
ALTER TABLE IF EXISTS ONLY public.chapter_progress DROP CONSTRAINT IF EXISTS ukj5kwa0fc7sftvp8w6n1puoixk;
ALTER TABLE IF EXISTS ONLY public.sheet DROP CONSTRAINT IF EXISTS sheet_pkey;
ALTER TABLE IF EXISTS ONLY public.resource DROP CONSTRAINT IF EXISTS resource_pkey;
ALTER TABLE IF EXISTS ONLY public.chapter_progress DROP CONSTRAINT IF EXISTS chapter_progress_pkey;
ALTER TABLE IF EXISTS ONLY public.chapter DROP CONSTRAINT IF EXISTS chapter_pkey;
ALTER TABLE IF EXISTS public.users ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.users_id_seq;
DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.sheet;
DROP TABLE IF EXISTS public.resource;
DROP TABLE IF EXISTS public.chapter_progress;
DROP TABLE IF EXISTS public.chapter;
-- *not* dropping schema, since initdb creates it
--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: chapter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chapter (
    chapter_id integer NOT NULL,
    chapter_name character varying(255),
    is_completed boolean NOT NULL,
    is_revised boolean NOT NULL,
    weightage double precision NOT NULL,
    sheet_id integer
);


--
-- Name: chapter_chapter_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chapter ALTER COLUMN chapter_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chapter_chapter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chapter_progress; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chapter_progress (
    id bigint NOT NULL,
    completed boolean NOT NULL,
    chapter_id integer NOT NULL,
    user_id bigint NOT NULL,
    revised boolean NOT NULL
);


--
-- Name: chapter_progress_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chapter_progress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chapter_progress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resource; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resource (
    resource_id integer NOT NULL,
    drive_fileid character varying(255) NOT NULL,
    resource_name character varying(255),
    type character varying(255),
    chapter_id integer,
    CONSTRAINT resource_type_check CHECK (((type)::text = ANY (ARRAY[('NOTES'::character varying)::text, ('SHORT_NOTES'::character varying)::text, ('PYQS'::character varying)::text])))
);


--
-- Name: resource_resource_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resource ALTER COLUMN resource_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_resource_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sheet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sheet (
    sheet_id integer NOT NULL,
    subject character varying(255),
    completed_chapters integer,
    description character varying(255),
    sheet_name character varying(255),
    total_chapters integer
);


--
-- Name: sheet_sheet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sheet ALTER COLUMN sheet_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sheet_sheet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    username character varying(255),
    password character varying(255) NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: chapter; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.chapter (chapter_id, chapter_name, is_completed, is_revised, weightage, sheet_id) FROM stdin;
24	d and f block Elements	f	f	0	2
1	Motion in a Plane	t	f	3	1
15	Electrons and Photons	t	f	0	1
2	Laws of Motion	t	t	5	1
3	Gravitation	t	f	3	1
4	Thermal Properties of Matter	t	f	3	1
5	Sound	t	t	3	1
6	Optics	t	f	5	1
7	Electrostatics	t	f	7	1
9	Circular Motion	t	f	4	1
30	Solid State	f	f	6	2
11	Oscillations	f	f	8	1
12	Wave Motion	t	f	5	1
32	Electrochemistry	f	f	6	2
33	p-Block Elements	f	f	2	2
13	Magnetic Effects of Electric Current	t	f	6	1
14	Electromagnetic Induction	t	f	6	1
36	Halogen Derivatives of Alkanes and Arenes	t	f	5	2
17	Kinetic Theory of Gases and Radiation	f	f	12	1
18	Wave Optics	t	f	7	1
19	Mechanical Properties of Fluids	t	f	4	1
20	Structure of Atom	t	f	3	2
21	Chemical Bonding	f	f	5	2
23	s-Block Elements	f	f	4	2
8	Semiconductors	t	f	0	1
27	Hydrocarbons	f	f	4	2
28	Basic Principles of Organic Chemistry	f	f	4	2
29	Chemistry in Everyday Life	f	t	3	2
31	Thermodynamics	f	f	4	2
34	d and f Block Elements	f	f	6	2
35	Chemical Kinetics	f	f	6	2
37	Aldehydes Ketones and Carboxylic Acids	t	f	6	2
38	Amines	t	f	5	2
40	Polymers	t	f	3	2
41	Trigonometry II	t	f	4	3
43	Circle	t	t	4	3
44	Measures of Dispersion	f	f	3	3
45	Complex Numbers	t	t	4	3
46	Permutations and Combinations	f	f	4	3
10	Rotational Motion	t	f	5.5	1
16	Dual Nature of Radiation and Matter	f	f	4	1
22	Redox Reactions	f	t	2	2
25	States of Matter (Gases and Liquids)	f	f	2	2
26	Surface Chemistry	f	f	2	2
39	Alcohols Phenols and Ethers	f	f	5	2
42	Straight Line	f	f	2	3
47	Limits	f	f	3	3
48	Continuity	f	f	3	3
49	Matrices	f	f	5	3
50	Pair of Straight Lines	f	f	4	3
51	Trigonometric Functions	t	f	4	3
52	Vectors	f	f	5	3
53	Line and Plane	t	f	5	3
54	Applications of Derivatives	f	f	5	3
55	Indefinite Integration	t	f	5	3
57	Applications of Definite Integral	t	f	3	3
62	Superposition of Waves	t	f	3	1
56	Differentiation	f	f	4	3
58	Differential Equations	t	f	5	3
59	Probability	f	f	6	3
60	AC CIrcuits	t	f	5	1
61	Thermodynamics	t	f	4	1
63	Definite Integration	f	f	6	3
\.


--
-- Data for Name: chapter_progress; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.chapter_progress (id, completed, chapter_id, user_id, revised) FROM stdin;
2	t	1	5	f
3	t	21	5	f
4	t	22	5	f
6	t	3	5	f
5	t	2	5	t
7	t	41	5	f
17	t	17	6	f
22	t	18	6	f
23	t	14	6	f
24	t	12	6	f
18	t	2	6	f
25	t	29	6	f
26	t	20	6	f
27	t	21	6	f
8	t	1	2	t
28	t	40	6	f
29	t	37	6	f
30	t	49	6	f
33	t	57	6	f
10	t	3	2	f
11	t	4	2	f
12	f	5	2	f
35	t	43	6	f
37	t	7	6	f
13	f	19	2	f
14	f	18	2	f
38	t	1	7	f
39	t	2	7	f
40	t	3	7	f
41	t	21	7	f
42	t	63	6	t
19	t	1	6	t
9	f	2	2	f
15	t	24	2	f
21	t	5	6	t
43	f	3	6	t
32	t	44	6	t
44	f	23	6	t
16	t	9	6	t
34	t	41	6	t
36	t	45	6	t
31	t	48	6	t
20	f	8	6	f
\.


--
-- Data for Name: resource; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.resource (resource_id, drive_fileid, resource_name, type, chapter_id) FROM stdin;
153	1H0TZVQgMejqSmKAaXM5NvRNkDfub-wnH	Motion in a Plane - Short Notes	SHORT_NOTES	1
154	1Y8Q32w2t0cAvYeNU3OlfBvT3IY-qdPl_	Laws of Motion - Notes	NOTES	2
155	1BwFsPuucT5jlZh1NWTGXr_qB0CsKjaJD	Laws of Motion - Short Notes	SHORT_NOTES	2
156	1E2sJLy28gB7BYsN1RW3AaNvfSiSJ5bIJ	Gravitation - Notes	NOTES	3
157	1wdVnJmAB1bI5VQkRlbp2qH8-MzKVvHyf	Gravitation - Short Notes	SHORT_NOTES	3
158	1H7gxBFjuPJVYWGaMr89KWBXVH5uNI1JH	Thermal Properties of Matter - Notes	NOTES	4
159	125unLb7PjucjPwoEZVaKK0A-3Z6g1gfD	Thermal Properties of Matter - Short Notes	SHORT_NOTES	4
160	1ckQalHGCYw_fELrqkVt79LnGe6IUllJq	Sound - Notes	NOTES	5
161	1wSZwQbNFwAM9e382QlnGZnU1Rm0XvxUN	Optics - PYQs	PYQS	6
162	1KpIawjXFRo7JwGLVsPjUlx7Xh-URuPkc	Electrostatics - Notes	NOTES	7
163	10niE57p3GrIdrqg1NPGbFQML2tYQv-LX	Electrostatics - Short Notes	SHORT_NOTES	7
164	10p4xdNYvndJw5IvLytK_figMFaxXAF7vg	Circular Motion - Notes	NOTES	9
165	1DHaC0xTgmV91NxADYrGj1HVWJrs2KCvY	Circular Motion - Short Notes	SHORT_NOTES	9
166	1XytQPG_pmxtMSeci1Yg54wDdlM4YG1vj	Oscillations - Notes	NOTES	11
167	1_48WIYIXUR4g1ZM504ymR0MG1mDeNYt1	Oscillations - Short Notes	SHORT_NOTES	11
168	1X-hkAgzGzg9co4fF3r5XOc4v8Hw1tjTI	Wave Motion - Notes	NOTES	12
169	1hP3j4pd4FDs6_F1Tn6awkqZ8bjdh_sPA	Magnetic Effects of Electric Current - Notes	NOTES	13
170	1-Uc-zZ8eJt2biXd6ALCfJvzh4Ek2QLgt	Magnetic Effects of Electric Current - Short Notes	SHORT_NOTES	13
171	1USEb3INbq3EKO1ACb1SruJjTNJUK6tSr	Electromagnetic Induction - Notes	NOTES	14
172	1prCPBVb_f5zfXnFAteFDZUL42iUNONcP	Dual Nature of Radiation and Matter - Notes	NOTES	16
173	1ueAwmlROgv0S0xDX-jSp6ZWqNlup3xdr	Dual Nature of Radiation and Matter - Short Notes	SHORT_NOTES	16
174	1gRzeCPHF9mYlWCVY8Z0nCVw6sg8agwNQ	Kinetic Theory of Gases and Radiation - Short Notes	SHORT_NOTES	17
175	1-DB1eIpSJBfm8x4nLFnMrl15ElFCGsaQ	Wave Optics - Notes	NOTES	18
176	16kldxty-kdzJRqFJ2q_ry9-CS3wTDO5i	Wave Optics - Short Notes	SHORT_NOTES	18
177	1GziAuyWt5vsi7a2b6jdtUi0xuiQWK9YM	Mechanical Properties of Fluids - Notes	NOTES	19
178	1DYjaxAjmCEEmtp2NrXbI6Xaa1FpkzL4D	Mechanical Properties of Fluids - Short Notes	SHORT_NOTES	19
179	1TNT_Vmku2giY3sdYjHdIKxO2HEdNcseJ	Structure of Atom - Notes	NOTES	20
180	1fOFggN9zQPORv_-DSHCTaUou_3k-LqZb	Chemical Bonding - Short Notes	SHORT_NOTES	21
181	1Jq6C24620hqtVyj6Pza-wg1Pv1o2Th9f	s-Block Elements - Short Notes	SHORT_NOTES	23
182	1_xh2fQ-18wClIf46iZL7Zj_FivxjU00s	d and f block Elements - Short Notes	SHORT_NOTES	24
183	1hkvqVyJVdcX05eDUOW3pDSu8ZdndY6KR	Hydrocarbons - Notes	NOTES	27
184	16kHji4_M_aBAfsS33SVW0vwpDar2JR0l	Basic Principles of Organic Chemistry - Notes	NOTES	28
185	1JsKF9wZG5ZBbChABS89viVXansb-Gxdb	Chemistry in Everyday Life - Notes	NOTES	29
186	1t-hYm2uThVgmroLKEbc0ObfRSiKOsllJ	Thermodynamics - Short Notes	SHORT_NOTES	31
187	1bsRwe2jRubCGBmaTajIsBwP95EKRm08k	Chemical Kinetics - Short Notes	SHORT_NOTES	35
188	1aOgsPlZ93Rv7UriGxjRM56ZhMhzN65vB	Aldehydes Ketones and Carboxylic Acids - Short Notes	SHORT_NOTES	37
189	12DzX1j_MZOM0_8je_lLTW-goMDu0_cK5	Amines - Short Notes	SHORT_NOTES	38
190	1POz6lwlHwWYVAyp8eWusD_fxN1KUt-mo	Polymers - Short Notes	SHORT_NOTES	40
191	1fcpXst8rpldizvfD3VRHF96Jmge7hmRe	Trigonometry II - Short Notes	SHORT_NOTES	41
192	1iZ3xxUQngJR-jA91jjSEVhjJEPINzZ5i	Circle - Short Notes	SHORT_NOTES	43
193	1JmRvFiUUAfru9EKPApySvcXvsLYZp5pg	Measures of Dispersion - Short Notes	SHORT_NOTES	44
194	1QiXev7e35YnVz58FEApBQ_0tvNpDFdea	Complex Numbers - Short Notes	SHORT_NOTES	45
195	1pGBIULM1JKf8gMbN4AKaulSlMBt03fzm	Permutations and Combinations - Short Notes	SHORT_NOTES	46
196	1BBwBWHHqQvOdDTdxHvV4SOufaiQtS2rt	Limits - Short Notes	SHORT_NOTES	47
197	18os5T-QjdIhShWvbEJiEhwhKZnStuo3j	Continuity - Short Notes	SHORT_NOTES	48
198	1tHBW8QHZJODIGGb4-2IYhIbTAY4-An6t	Matrices - Short Notes	SHORT_NOTES	49
199	1D6ggauRwnAuRcpR7zFj3-cTgaMidD6I4	Pair of Straight Lines - Short Notes	SHORT_NOTES	50
200	1FfqPE7EwAuYY1QYjy3j3HqFMcVsC4-mX	Trigonometric Functions - Short Notes	SHORT_NOTES	51
201	1rX_2lglAmgGHJ4CFbqM0J_T184NnKYaj	Vectors - Short Notes	SHORT_NOTES	52
202	1iSOxetCGrUhdIukVPVCe1CIdwRBOvtIz	Line and Plane - Short Notes	SHORT_NOTES	53
203	1AuU81QtQGqVvK4ffm9kcdFBnBAsTpiyY	Applications of Derivatives - Short Notes	SHORT_NOTES	54
204	1vfJSWLXQzPogK2tiDbeFpzi8EivTBr_-	Indefinite Integration - Notes	NOTES	55
205	1Ubc0ZSko67wFpQu6bAp6Fw7_WFvpxB7N	Indefinite Integration - Short Notes	SHORT_NOTES	55
206	13us-j9i7kvex9rK00E37znvs3iNGJG2P	Definite Integration - Short Notes	SHORT_NOTES	63
207	1u405-spAECT0zsv2LLlW4FX9KWHStNev	Differentiation - Short Notes	SHORT_NOTES	56
208	1nxxslQBFrmS4MByi1iLXunjXQeUgCqoV	Applications of Definite Integral - Short Notes	SHORT_NOTES	57
209	1L5tebz4V5yxlOQR16V9Rv1-3hNhUoZHQ	Differential Equations - Short Notes	SHORT_NOTES	58
210	1X4MAijfUzXMqhdQ7ScwmP9UNLn-Bstb5	Probability - Short Notes	SHORT_NOTES	59
211	19udi0mCWe7fio5HCF65yAAASP17wHJOq	AC Circuits - Short Notes	SHORT_NOTES	60
212	1GCEDH_QyKKGus5-6m9TTK6oMNFpr4kHv	Thermodynamics - Short Notes	SHORT_NOTES	61
213	13UqSGCfI8tiNCLEgWD2Jn7IvWrTGDWYv	Superposition of Waves - Short Notes	SHORT_NOTES	62
\.


--
-- Data for Name: sheet; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.sheet (sheet_id, subject, completed_chapters, description, sheet_name, total_chapters) FROM stdin;
1	Physics	0	Complete Physics CET syllabus	Physics CET Syllabus	0
2	Chemistry	0	Complete Chemistry CET syllabus	Chemistry CET Syllabus	0
3	Mathematics	0	Complete Mathematics CET Syllabus	Mathematics CET Syllabus	0
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, email, username, password) FROM stdin;
1	c@gmail.com	c	$2a$10$Kla.4j4mkQKujxgQN4ku8.wYGo7/JKqYXz05pbqdoLrvBkfoGL/rK
2	b@gmail.com	b	$2a$10$UM6Y4giepoupoYQtOL6cRu.r3P3Vtowu0UR016CjqvuIbCcOe9vsq
3	d@gmail.com	d	$2a$10$WNqhZQ.HPod.OmZTbjqtf.UgSNZLsey14ZBa.xJPG4VYGe2xqH9c.
4	e@gmail.com	e	$2a$10$hUSiHydCHJCvkbC71xocHuSa/SofGl4PWZG9ynu/YsJDzONS2KeN6
5	f@gmail.com	f	$2a$10$vGOwDWslmhWbjZwgfCwyaO9904RONzjaj6RHZ8IduloNjexC5lB1m
6	shashwat@gmail.com	shashwat@gmail.com	$2a$10$dhIl6IcfD55j3VH0PSLp1uLx8IPn.dYYwcXDhJ0zrF8BTDn8hScca
7	virat@gmail.com	virat@gmail.com	$2a$10$kWywED7nBLB8W/ASUZoJ/Ome4nuAMJE9rjRPilHeJGcDOcGV88/4W
8	shashh.code@gmail.com	ShashCode	$2a$10$QCYOV2KUfbXT/MTEUF9WD.MMjeVUYBdKni0n3HxKDTxFNTYt3Gjiu
9	shashwat.diwan23@vit.edu	SHASHWAT DIWAN	$2a$10$MlRHxBH2vlSxSRAt56qYMefjLiL26kyDBU4cjG5pfqm5/IbabNdDa
\.


--
-- Name: chapter_chapter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.chapter_chapter_id_seq', 1, false);


--
-- Name: chapter_progress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.chapter_progress_id_seq', 44, true);


--
-- Name: resource_resource_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.resource_resource_id_seq', 213, true);


--
-- Name: sheet_sheet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.sheet_sheet_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 9, true);


--
-- Name: chapter chapter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter
    ADD CONSTRAINT chapter_pkey PRIMARY KEY (chapter_id);


--
-- Name: chapter_progress chapter_progress_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter_progress
    ADD CONSTRAINT chapter_progress_pkey PRIMARY KEY (id);


--
-- Name: resource resource_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource
    ADD CONSTRAINT resource_pkey PRIMARY KEY (resource_id);


--
-- Name: sheet sheet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sheet
    ADD CONSTRAINT sheet_pkey PRIMARY KEY (sheet_id);


--
-- Name: chapter_progress ukj5kwa0fc7sftvp8w6n1puoixk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter_progress
    ADD CONSTRAINT ukj5kwa0fc7sftvp8w6n1puoixk UNIQUE (user_id, chapter_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email ON public.users USING btree (email);


--
-- Name: chapter fkc9w9kmbmff4v3oeij0pa5vm2e; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter
    ADD CONSTRAINT fkc9w9kmbmff4v3oeij0pa5vm2e FOREIGN KEY (sheet_id) REFERENCES public.sheet(sheet_id);


--
-- Name: chapter_progress fklk6rkos5dm8jxdpms4xo8ksov; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter_progress
    ADD CONSTRAINT fklk6rkos5dm8jxdpms4xo8ksov FOREIGN KEY (chapter_id) REFERENCES public.chapter(chapter_id);


--
-- Name: resource fkmeif6ix75gdnvpopg3d6gmaa6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resource
    ADD CONSTRAINT fkmeif6ix75gdnvpopg3d6gmaa6 FOREIGN KEY (chapter_id) REFERENCES public.chapter(chapter_id);


--
-- Name: chapter_progress fkv4lcvj8xomcv3tmeylctrldg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chapter_progress
    ADD CONSTRAINT fkv4lcvj8xomcv3tmeylctrldg FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

